
import database.koneksi_db;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ali Rohmat
 */
public class Crud extends javax.swing.JFrame {
    koneksi_db conn;
    ResultSet rs;
    DefaultTableModel table = new DefaultTableModel();  
    /**
     * Creates new form Crud
     */
    public Crud() {
        initComponents();
        
        conn = new koneksi_db(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        Tselect.setModel(table);
        table.addColumn("ID");
        table.addColumn("Nama User");
        table.addColumn("Password");
        loadTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tselect = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Juser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jpass = new javax.swing.JPasswordField();
        Bsimpan = new javax.swing.JButton();
        Bupdate = new javax.swing.JButton();
        Jid = new javax.swing.JLabel();
        Bdelete = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        BcA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tselect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tselect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TselectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tselect);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("CRUD Database");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        Bsimpan.setText("Buat");
        Bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsimpanActionPerformed(evt);
            }
        });

        Bupdate.setText("Edit");
        Bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupdateActionPerformed(evt);
            }
        });

        Jid.setText("jLabel1");

        Bdelete.setText("Hapus Data");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });

        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });

        BcA.setText("Hapus Semua Data");
        BcA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jid))
                    .addComponent(Juser)
                    .addComponent(Jpass)
                    .addComponent(BcA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bdelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(Bsimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Breset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Jid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Juser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Breset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BcA))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TselectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TselectMouseClicked
        Jid.setText(String.valueOf(Tselect.getValueAt(Tselect.getSelectedRow(),0)));
        Juser.setText(String.valueOf(Tselect.getValueAt(Tselect.getSelectedRow(),1)));
        Jpass.setText(String.valueOf(Tselect.getValueAt(Tselect.getSelectedRow(),2)));
    }//GEN-LAST:event_TselectMouseClicked

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        this.reset();
    }//GEN-LAST:event_BresetActionPerformed

    private void BsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsimpanActionPerformed
        String[] tabel = { "username" , "password" };
        String user = Juser.getText().toString();
        String pass = Jpass.getText().toString();
        String[] insert ={user, pass};
        this.create_akun(tabel, insert);
        this.loadTabel();
        this.reset();
    }//GEN-LAST:event_BsimpanActionPerformed

    private void BupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupdateActionPerformed
        String[] tabel = { "username" , "password" };
        String id = Jid.getText().toString();
        String user = Juser.getText().toString();
        String pass = Jpass.getText().toString();
        String[] update ={user, pass};
        String KOndisi = "id = " + id;
        this.update_akun(tabel, update, KOndisi);
        this.loadTabel();
        this.reset();
    }//GEN-LAST:event_BupdateActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed
        String id = Jid.getText().toString();
        String kondisi = "id = " + id ;
        this.delete_akun(kondisi);
        this.loadTabel();
        this.reset();
    }//GEN-LAST:event_BdeleteActionPerformed

    private void BcAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcAActionPerformed
        this.delete_all();
        this.loadTabel();
    }//GEN-LAST:event_BcAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BcA;
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Breset;
    private javax.swing.JButton Bsimpan;
    private javax.swing.JButton Bupdate;
    private javax.swing.JLabel Jid;
    private javax.swing.JPasswordField Jpass;
    private javax.swing.JTextField Juser;
    private javax.swing.JTable Tselect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void reset() {
        Jid.setText("");
        Juser.setText("");
        Jpass.setText("");
    }

    private void loadTabel() {
        int row = Tselect.getRowCount();
        for(int a = 0 ; a < row ; a++){
        table.removeRow(0);}
        try{
            rs = conn.querySelectAll("users");
            while (rs.next()){
                String txid_ = rs.getString("id");
                String txuser = rs.getString("username");
                String txpass = rs.getString("password");
                
                String data[] = {txid_, txuser, txpass};
                
                table.addRow(data);
            }
            Tselect.setModel(table);
        }catch(Exception e){
            System.out.print(e);
        }
    }
    
    public void create_akun(String[] kolom ,String[] buat){
        conn = new koneksi_db(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        conn.queryInsert("users", kolom , buat);
    }

    public void update_akun(String[] kolom ,String[] buat, String kondisi){
        conn = new koneksi_db(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        conn.queryUpdate("users", kolom , buat,kondisi);
    }
    
    public void delete_akun(String kondisi){
        conn = new koneksi_db(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        conn.queryDelete("users",kondisi);
    }
    
    public void delete_all(){
        conn = new koneksi_db(new database.parameter().HOST_DB, new database.parameter().USERNAME_DB, new database.parameter().PASSWORD_DB);
        conn.queryDelete("users");
    }
}
